### ISSUE TITLE
odoo12 安装时报错：psycopg2.ProgrammingError: 错误:  关系 "celery_taskmeta" 不存在

### ISSUE THREAD

**Issue by digitalliuzg** [JoneXiong/task_queue#1]
Odoo Server Error
Traceback (most recent call last):
  File "E:\odoo\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\odoo\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "E:\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "E:\odoo\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "E:\odoo\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\odoo\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\odoo\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "E:\odoo\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "e:\odoo\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "e:\odoo\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\odoo\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "E:\odoo\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "e:\odoo\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "e:\odoo\odoo\addons\base\models\ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "e:\odoo\odoo\addons\base\models\ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "E:\odoo\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "E:\odoo\odoo\modules\loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "E:\odoo\odoo\modules\loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "E:\odoo\odoo\modules\loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "E:\odoo\odoo\modules\registry.py", line 297, in init_models
    model.init()
  File "e:\source\otheraddons\task_queue\models.py", line 42, in init
    )""" % self._table)
  File "E:\odoo\odoo\sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "E:\odoo\odoo\sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: 错误:  关系 "celery_taskmeta" 不存在
LINE 2:             select * from celery_taskmeta order by id desc

**Comment by JoneXiong** [comment]
更新版本，基于db的实现无依赖问题
